const words = [ ["tellement", "astfel, astfel de"],/// 0 - sec1
  ["faible", "slab", "sans force de caractère"],
  ["copain", "prieten"],
  ["ensemble", "împreună"],
  ["sourtout", "mai ales"],
  ["voisin", "vecin"],
  ["sortir", "a ieși"],
  ["mur", "perete"],
  ["entrer", "a intra"],
  ["entre", "între"],
  ["cartable", "ghiozdan"],
  ["yeux", "ochi"],
  ["cheveux", "păr"],
  ["court", "scurt"],
  ["lunettes", "ochelari"],
  ["bientôt", "curând, în curând"],
  ["maigre", "slab", "apparence physique"],
  ["hiver", "iarnă"],
  ["chaud", "cald"],
  ["chez", "la"],
  ["souhaiter", "a dori"],
  ["sympa", "simpatic"],
  ["allemand", "german"],
  ["vieux", "bătrân"],
  ["vieille", "bătrână"],
  ["beau", "frumos"],
  ["belle", "frumoasă"],
  ["sage", "înțelept"],
  ["malade", "bolnav"],
  ["joli", "drăguț"],
  ["bavard", "vorbăreț, guraliv"],
  ["sourire", "a zâmbi"],
  ["méchant", "rău, obraznic"],
  ["sauvage", "sălbatic"],
  ["haut", "înalt"],
  ["ordinateur", "calculator"],
  ["chaîne hi-fi", "radio"],
  ["poupée", "păpușă"],
  ["École maternelle", "grădiniță"],
  ["école élémentaire", "școală primară"],   /// 40 - sec2
  ["gymnase", "gimnaziu"],
  ["lycée", "liceu"],
  ["souvent", "adesea, des, de multe ori"],
  ["après-midi", "după-amiază"],
  ["loin", "departe"],
  ["mauvais", "rău"],
  ["clair", "clar"],
  ["chaise", "scaun"],
  ["autour", "în jur"],
  ["poulet", "pui"],
  ["fromage", "brânză"],
  ["gâteau", "tort, prăjitură"],
  ["taille-crayon", "ascuțitoare"],
  ["bâton", "băț"],
  ["colle", "adeziv, clei, lipici"],
  ["clé", "cheie"],
  ["boîte", "cutie"],
  ["carte", "hartă"],
  ["trousse", "penar, trusa"],
  ["pied", "picior"],
  ["à pied", "pe jos"],
  ["promenade", "plimbare"],
  ["près", "aproape"],
  ["devant de", "înainte de, în fața", "de position"],
  ["devant", "a trebui", "action"],
  ["sur", "pe"],
  ["sous", "sub"],
  ["à côté de", "lângă"],
  ["en face", "în fața"],
  ["au milieu", "în mijloc, la mijloc"],
  ["dans", "în"],
  ["en", "în"],
  ["derrière", "în spate"],
  ["gauche", "stânga"],
  ["droit", "dreapta", "position"],
  ["droit", "drept", "appartient à l'homme"],
  ["maintenant", "acum"],
  ["où", "unde"],
  ["ou", "sau"],                                 /// 80 - sec3
  ["chasseur", "vânător"],
  ["facteur", "poștaș"],
  ["coiffeur", "frizer, coafor"],
  ["vendeuse", "vânzătoare"],
  ["coeur", "inimă"],
  ["boeuf", "vită"],
  ["ruisseau", "pârâu, curent de apa"],
  ["vite", "rapid"],
  ["accueil", "bine ați venit, binevenit"],
  ["rompre", "a rupe"],
  ["gérer", "a gestiona"],
  ["concernant", "referitor la, în ceea ce privește"],
  ["conviction", "convingere"],
  ["achever", "a finaliza, a termina, a încheia"],
  ["notamment", "în special, îndeosebi"],
  ["ainsi", "astfel, așa că"],
  ["certes", "cu siguranță, cu certitudine"],
  ["pourtant", "încă"],
  ["cependant", "totusi, cu toate acestea"],
  ["toutefois", " în orice caz"],
  ["et puis", "și apoi"],
  ["en effet", "întradevăr, cu adevărat"],
  ["choix", "alegere"],
  ["matin", "dimineață"],
  ["demie", "jumătate"],
  ["quart", "sfert, un sfert"],
  ["habiter", "a locui"],
  ["nager", "a înota"],
  ["travailler", "a lucra"],
  ["rendre", "a se întoarce, a întoarce"],
  ["corriger", "a corecta"],
  ["painer", "coș"],
  ["pain", "pâine"],
  ["rougir", "a roși"],
  ["rouge", "roșu"],
  ["vert", "verde"],
  ["bleu", "albastru"],
  ["jaune", "galben"],
  ["orange", "portocaliu, oranj"],
  ["brun", "maro"],                           /// 120 - sec4
  ["rose", "roz"],
  ["violet", "violet"],
  ["bien sûr", "bineînțeles, desigur"],
  ["blanc", "alb"],
  ["gris", "gri"],
  ["noir", "negru"],
  ["vif", "viu"],
  ["foncé", "închis", 'une couleur ___'],
  ["pâle", "palid, deschis"],
  ["clair", "deschis", "une couleur ___"]
  ["mettre", "a pune"],
  ["aller", "a merge"],
  ["venir", "a veni"],
  ["dire", "a spune, a zice"],
  ["écrire", "a scri"],
  ["prendre", "a lua"],
  ["partir", "a pleca"],
  ["à l'heure", "la timp"],
  ["retirer", "a retrage, a scoate"],
  ["casque", "cască"],
  ["capuche", "glugă"],
  ["mâcher", "a mesteca"],
  ["courteau", "cuțit"],
  ["bruit", "zgomot"],
  ["couloir", "hol, coridor"],
  ["poubelle", "coș de gunoi"],
  ["bagarrer", "a se bate, a se lupta"],
  ["toucher", "a atinge"],
  ["signer", "a semna"],
  ["si", "dacă"],
  ["laver", "a spăla"],
  ["habiller", "a se îmbrăca, a îmbrăca"],
  ["vers", "către, spre, pe la"],
  ["moins", "mai puțin"],
  ["après", "după"],
  ["goûter", "a gusta"],
  ["lit", "pat"],
  ["aller au lit", "a merge la culcare, a se duce la culcare"],
  ["sortie", "ieșire"],
  ["assez", "destul de"],                        /// 160 - sec5
  ["mince", "subțire"],
  ["boucle", "buclat, creț"],
  ["bord", "margine", "le ___ d'un objet"],
  ["bord", "mal", "le ___ du mer méditerranée"]
  ["natale de", "locuit de"],
  ["lundi", "luni"],
  ["mardi", "marți"],
  ["mercredi", "miercuri"],
  ["jeudi", "joi"],
  ["vendredi", "vineri"],
  ["samedi", "sâmbătă"],
  ["dimanche", "duminică"],
  ["froid", "rece"],
  ["appareil", "dispozitiv, aparat"],
  ["bonne humeur", "dispoziție bună"],
  ["coucher du soleil", "apus"],
  ["lever du soleil", "rasarit"],
  ["c'est en fer", "este din fier, este facut din fier"],
  ["étroit", "îngust"],
  ["épais", "gros"],
  ["plafon", "tavan"],
  ["bas", "jos"],
  ["basse", "joasă"],
  ["printemps", "primăvară"],
  ["été", "vară"],
  ["automne", "toamnă"],
  ["lapin", "iepure"],
  ["serpent", "șarpe"],
  ["champ", "câmp"],
  ["properté", "curățenie"],
  ["tronc", "trunchi"],
  ["folle", "nebun, Solomon Nicoleta"],
  ["gros", "gras"],
  ["qui importe", "care contează"],
  ["perroquent", "papagal"],
  ["loup", "lup"],
  ["oiseau", "pasare"],
  ["chévre", "capră"],
  ["nez", "nas"],
  ["en fait", "defapt"],                        /// 200 - sec6
  ["dernier", "ultimul, ultima"],
  

  //ăâșțîéèàùçêôû
];

export default words;